# Generated by Django 4.1.7 on 2024-04-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeredquestion",
            name="user_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answered_questions",
                to="users.usercourse",
            ),
        ),
        migrations.AddField(
            model_name="completedcontent",
            name="user_course",
            field=models.ForeignKey(
                default="da226807-41c1-45a1-a448-24cebd895ba7",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_contents",
                to="users.usercourse",
            ),
            preserve_default=False,
        ),
    ]
