# Generated by Django 4.1.7 on 2024-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_answeredquestion_user_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_expiration_task_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
