# Generated by Django 4.1.7 on 2024-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token_expiration_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="cut_off_score",
            field=models.FloatField(default=0),
        ),
    ]
