# Generated by Django 4.1.7 on 2024-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_department_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="campaign_completion_notifcation",
            field=models.BooleanField(
                default=True,
                verbose_name="Employees receive an email every time they complete a campaign",
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="campaign_email_notifiction",
            field=models.BooleanField(
                default=True,
                verbose_name="Employees receive an email with every new campaign they are enrolled in",
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="reminder_notification",
            field=models.BooleanField(
                default=True,
                verbose_name="Employees receive an email and reminders, instructing them to complete the campaign before the deadline.",
            ),
        ),
    ]
