# Generated by Django 4.1.7 on 2024-04-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_organizationprofile_campaign_completion_notifcation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationprofile",
            old_name="campaign_completion_notifcation",
            new_name="campaign_completion_notification",
        ),
    ]
