# Generated by Django 4.1.7 on 2024-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0007_rename_campaign_completion_notifcation_organizationprofile_campaign_completion_notification",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationprofile",
            old_name="campaign_email_notifiction",
            new_name="campaign_email_notification",
        ),
    ]
