# Generated by Django 4.1.7 on 2024-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_organizationprofile_phishing_report_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizeddomain",
            name="verification_background_task_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="authorizeddomain",
            name="verification_code",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="authorizeddomain",
            name="verification_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
