# Generated by Django 4.1.7 on 2024-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_authorizeddomain_verification_background_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizeddomain",
            name="sent_to",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="authorizeddomain",
            name="domain",
            field=models.CharField(max_length=256),
        ),
    ]
