# Generated by Django 4.1.7 on 2024-04-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_authorizeddomain_sent_to_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorizeddomain",
            old_name="sent_to",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="authorizeddomain",
            name="verification_code",
        ),
    ]
