# Generated by Django 4.1.7 on 2024-05-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="action",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="type",
            field=models.CharField(
                choices=[
                    ("course_campaign_started", "Course Campaign Started"),
                    ("course_campaign_completed", "Course Campaign Completed"),
                    ("course_started", "Course Started"),
                    ("course_completed", "Course Completed"),
                ],
                default="course_campaign_started",
                max_length=256,
            ),
        ),
    ]
