# Generated by Django 4.1.7 on 2024-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_activitylog_action_activitylog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="security_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
