# Generated by Django 4.1.7 on 2024-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_employeeprofile_security_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="security_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
