# Generated by Django 4.1.7 on 2024-05-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_employeeprofile_security_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="security_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="security_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
