# Generated by Django 4.1.7 on 2024-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_department_security_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_started",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
