# Generated by Django 4.1.7 on 2024-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_usertimeseriessecurityscore_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertimeseriescompletedcourses",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
