# Generated by Django 4.1.7 on 2024-04-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="employees",
        ),
    ]
