# Generated by Django 4.1.7 on 2024-04-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_remove_campaign_employees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="departments",
        ),
    ]
