# Generated by Django 4.1.7 on 2024-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("content", "0002_initial"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_questions",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="campaigncontentquiz",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_questions",
                to="content.campaigncontentsnapshot",
            ),
        ),
    ]
