# Generated by Django 4.1.7 on 2024-04-10 10:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
        ("content", "0002_initial"),
        ("users", "0002_answeredquestion_user_course_and_more"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCourseCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("is_started", models.BooleanField(default=False)),
                ("is_expired", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_records",
                        to="courses.coursecampaign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_campaign_records",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedCourseCampaignContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_contents",
                        to="content.content",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_contents",
                        to="courses.course",
                    ),
                ),
                (
                    "course_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_contents",
                        to="courses.coursecampaign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_contents",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnsweredCourseCampaignQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("question_options_snapshot", models.JSONField(default=dict)),
                ("answers_snapshot", models.JSONField(default=dict)),
                (
                    "answers",
                    models.ManyToManyField(blank=True, to="quiz.questionoption"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_campaign_questions",
                        to="content.content",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_campaign_questions",
                        to="courses.course",
                    ),
                ),
                (
                    "course_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_campaign_questions",
                        to="courses.coursecampaign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answered_campaign_questions",
                        to="users.employee",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="coursecampaign",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="course_campaign",
                through="courses.EmployeeCourseCampaign",
                to="users.employee",
            ),
        ),
    ]
