# Generated by Django 4.1.7 on 2024-04-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_employeecoursecampaign_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecoursecampaign",
            name="is_active",
        ),
    ]
