# Generated by Django 4.1.7 on 2024-04-24 14:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token_expiration_task_id"),
        ("courses", "0005_remove_employeecoursecampaign_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCampaignCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign",
                        to="courses.course",
                    ),
                ),
                (
                    "course_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_courses",
                        to="courses.coursecampaign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_campaign_courses",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="CompletedCourseCampaignCourse",
        ),
        migrations.AddField(
            model_name="completedcoursecampaigncontent",
            name="course_campaign_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_campaign_contents",
                to="courses.coursecampaigncourse",
            ),
        ),
    ]
