# Generated by Django 4.1.7 on 2024-04-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token_expiration_task_id"),
        ("courses", "0006_coursecampaigncourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecampaigncourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursecampaigncourse",
            name="course_campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_courses",
                to="courses.coursecampaign",
            ),
        ),
        migrations.AlterField(
            model_name="coursecampaigncourse",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_courses",
                to="users.employee",
            ),
        ),
    ]
