# Generated by Django 4.1.7 on 2024-04-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_coursecampaigncourse_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecampaigncourse",
            name="course_campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_courses",
                to="courses.coursecampaign",
            ),
        ),
    ]
