# Generated by Django 4.1.7 on 2024-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_coursecampaigncourse_course_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecampaign",
            name="reminder_task_ids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
