# Generated by Django 4.1.7 on 2024-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_course_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/contents/"
            ),
        ),
    ]
