# Generated by Django 4.1.7 on 2024-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningrecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_records",
                to="users.employee",
            ),
        ),
    ]
