# Generated by Django 4.1.7 on 2024-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("phishing", "0001_initial"),
        ("campaign", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingtemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phishing_templates",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="phishingcampaignrecord",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phishing_records",
                to="campaign.campaign",
            ),
        ),
        migrations.AddField(
            model_name="phishingcampaignrecord",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phishing_records",
                to="users.employee",
            ),
        ),
        migrations.AddField(
            model_name="phishingcampaignrecord",
            name="phishing_campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="phishing.phishingcampaign",
            ),
        ),
        migrations.AddField(
            model_name="phishingcampaign",
            name="campaign",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phishing_campaign",
                to="campaign.campaign",
            ),
        ),
        migrations.AddField(
            model_name="phishingcampaign",
            name="phishing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phishing_campaigns",
                to="phishing.phishingtemplate",
            ),
        ),
    ]
