# Generated by Django 4.1.7 on 2024-04-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0004_phishingtemplate_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phishingtemplate",
            old_name="email_body",
            new_name="email_css_styles",
        ),
        migrations.AddField(
            model_name="phishingtemplate",
            name="email_html_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
