# Generated by Django 4.1.7 on 2024-04-23 14:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_answeredquestion_user_course_and_more"),
        (
            "phishing",
            "0005_rename_email_body_phishingtemplate_email_css_styles_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePhishingCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "compromised_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_email_sent", models.BooleanField(default=False)),
                ("is_opened", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                ("is_compromised", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phishing_campaign_records",
                        to="users.employee",
                    ),
                ),
                (
                    "phishing_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_records",
                        to="phishing.phishingcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="phishingcampaign",
            name="employees",
        ),
        migrations.AddField(
            model_name="phishingcampaign",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="phishing_campaigns",
                through="phishing.EmployeePhishingCampaign",
                to="users.employee",
            ),
        ),
    ]
