# Generated by Django 4.1.7 on 2024-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0006_employeephishingcampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeephishingcampaign",
            name="action",
            field=models.CharField(
                default="no_action",
                max_length=256,
                verbose_name="Highest Action based on risk rating",
            ),
        ),
    ]
