# Generated by Django 4.1.7 on 2024-04-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0007_employeephishingcampaign_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeephishingcampaign",
            name="action",
            field=models.CharField(
                choices=[
                    ("clicked", "Clicked"),
                    ("opened", "Opened"),
                    ("compromised", "Compromised"),
                    ("reported", "Reported"),
                    ("no_action", "No Action"),
                ],
                default="no_action",
                max_length=256,
                verbose_name="Highest Action based on risk rating",
            ),
        ),
    ]
