# Generated by Django 4.1.7 on 2024-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0008_alter_employeephishingcampaign_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phishingcampaign",
            name="phishing_snapshot",
        ),
        migrations.AddField(
            model_name="employeephishingcampaign",
            name="background_task_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
