# Generated by Django 4.1.7 on 2024-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0009_remove_phishingcampaign_phishing_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingtemplate",
            name="email_use_ssl",
            field=models.BooleanField(default=False),
        ),
    ]
