# Generated by Django 4.1.7 on 2024-05-08 11:02

from django.db import migrations, models

cache = {}


def store_phishing(apps, schema_editor):

    PhishingCampaign = apps.get_model("phishing", "PhishingCampaign")
    for phishing_campaign in PhishingCampaign.objects.all():
        if phishing_campaign.phishing:
            cache[phishing_campaign.id] = phishing_campaign.phishing.id


def restore_phishing(apps, schema_editor):
    PhishingCampaign = apps.get_model("phishing", "PhishingCampaign")
    PhishingTemplate = apps.get_model("phishing", "PhishingTemplate")
    for key, value in cache.items():
        phishing_campaign = PhishingCampaign.objects.get(id=key)
        phishing_template = PhishingTemplate.objects.filter(id=value).first()
        if phishing_template:
            phishing_campaign.phishing_templates.add(phishing_template)


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0010_phishingtemplate_email_use_ssl"),
    ]

    operations = [
        # migrations.RunPython(store_phishing),
        migrations.RemoveField(
            model_name="phishingcampaign",
            name="phishing",
        ),
        migrations.AddField(
            model_name="phishingcampaign",
            name="phishing_templates",
            field=models.ManyToManyField(
                related_name="phishing_campaigns", to="phishing.phishingtemplate"
            ),
        ),
        # migrations.RunPython(restore_phishing),
    ]
