# Generated by Django 4.1.7 on 2024-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0012_employeephishingcampaign_phishing_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeephishingcampaign",
            name="security_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
