# Generated by Django 4.1.7 on 2024-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0013_employeephishingcampaign_security_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingtemplate",
            name="landing_page_html_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
