# Generated by Django 4.1.7 on 2024-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0014_phishingtemplate_landing_page_html_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingtemplate",
            name="landing_page_css_styles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
