# Generated by Django 4.1.7 on 2024-04-08 16:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignContentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.JSONField()),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="File name"
                    ),
                ),
                (
                    "path",
                    models.URLField(
                        blank=True, null=True, verbose_name="S3 Bucket url"
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=5, null=True)),
                ("is_uploaded", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("video", "Video"),
                            ("illustration", "Illustration"),
                            ("slideshow", "Slideshow"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "learning_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "General"),
                            ("specialized", "Specialized"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "instructor_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Duration in seconds",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
