# Generated by Django 4.1.7 on 2024-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("content", "0001_initial"),
        ("campaign", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="campaigncontentsnapshot",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_content_snapshots",
                to="campaign.campaign",
            ),
        ),
    ]
