# Generated by Django 4.1.7 on 2024-04-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="duration",
        ),
    ]
