# Generated by Django 4.1.7 on 2024-04-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_content_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
