# Generated by Django 4.1.7 on 2024-04-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_content_duration"),
        ("content", "0004_content_duration"),
    ]

    operations = []
