# Generated by Django 4.1.7 on 2024-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_content_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contents/"),
        ),
    ]
