# Generated by Django 4.1.7 on 2024-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_content_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="size",
            field=models.FloatField(default=0),
        ),
    ]
