name: Django Tests

on: [push]

jobs:
  tests:
    name: Django Tests
    runs-on: ubuntu-latest
    services:
      # postgres:
      #   image: postgres
      #   env:
      #     POSTGRES_DB: postgres
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #     POSTGRES_HOST: localhost
      #     POSTGRES_PORT: 5432
      #   ports:
      #     - 5432:5432
      #   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Make migrations
        run: |
          python manage.py migrate
          python manage.py loaddata courses contents course_content
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8
      - name: Run tests
        run: |
          python manage.py test
